name: Create Wiki from Word Docs
on: [push, workflow_dispatch]
concurrency:
  group: wiki
  cancel-in-progress: true
permissions:
  contents: write
jobs:
  convert:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Cache APT Packages
        uses: awalsh128/cache-apt-pkgs-action@v1
        with:
          packages: pandoc
          version: 1.0
          execute_install_scripts: true

      - name: Convert all Word docs to GitHub Markdown
        run: |
          mkdir -p "./wiki"
          cd ./wiki
          find .. -type f -name "*.docx" | while read -r file; do
            # Get relative path, sanitize it for folder names, and set up output directories
            rel_path="${file#./}"
            sanitized_rel_path=$(echo "$rel_path" | sed 's/ /-/g')
            doc_name=$(basename "${sanitized_rel_path%.docx}")
            output_dir="./$(dirname "$sanitized_rel_path")"
            image_dir="/images/$doc_name"
            mkdir -p "$output_dir"
            mkdir -p "$image_dir"
            
            # Set up markdown output file path and convert with images in document-specific folder
            output_file="$output_dir/$doc_name.md"
            pandoc --from docx --to gfm --extract-media="$image_dir" "$file" -o "$output_file"
            
            echo "Converted: $file -> $output_file with images in $image_dir"
          done
          cd ..

      - name: Publish wiki
        uses: ineshbose/wiki-action@v1
        with:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WIKI_DIR: 'wiki'
          AUTO_SIDEBAR: true
